version: '2'
services:
  ide:
    image: psharkey/intellij:latest
#    image: psharkey/netbeans-8.1:latest
    environment:
      - DISPLAY=novnc:0.0
    depends_on:
      - novnc
    networks:
      - x11
  novnc:  
  #image: theasp/novnc:latest
    build: .
    environment:
      # Adjust to your screen size
      - DISPLAY_WIDTH=1600
      - DISPLAY_HEIGHT=968
    volumes:
      - './data/downloads:/root/Downloads/115download/'
    ports:
      - "8080:8080"
    networks:
      - x11
networks:
  x11:
