name: docker-push
on: push
jobs:
  docker:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags')
    strategy:
      matrix:
        include:
          - app: python3-weasyprint
            repo: python
            pre: python3-weasyprint-
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Extract Version
        id: version_step
        run: |
          echo "##[set-output name=version;]VERSION=${GITHUB_REF#$"refs/tags/v"}"
          echo "##[set-output name=version_tag;]${{ matrix.repo }}:${{ matrix.pre }}${GITHUB_REF##*-}"
          echo "##[set-output name=latest_tag;]${{ matrix.repo }}:${{ matrix.pre }}latest"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.app }}
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{steps.version_step.outputs.version_tag}}
            ${{ secrets.DOCKER_USERNAME }}/${{steps.version_step.outputs.latest_tag}}
          build-args: |
            ${{steps.version_step.outputs.version}}
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/${{ matrix.repo }}
          readme-filepath: ./${{ matrix.app }}/README.md
