name: docker-push
on: push
jobs:
  docker:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags')
    strategy:
      matrix:
        app-list:
          # - novnc
          - novnc-wp115
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Extract Version
        id: version_step
        run: |
          [ -f "./${{ matrix.app-list }}/VERSION" ] && . ./${{ matrix.app-list }}/VERSION
          [ -z "$version" ] && version=${GITHUB_REF#$"refs/tags/v"}
          [ -z "$version_tag" ] && version_tag="${GITHUB_REF##*-}"
          [ -z "$latest_tag" ] && latest_tag="latest"
          echo "version=VERSION=${version}" >> "$GITHUB_OUTPUT"
          echo "version_tag=${{ secrets.DOCKER_USERNAME }}/${{ matrix.app-list }}:${version_tag}" >> "$GITHUB_OUTPUT"
          echo "latest_tag=${{ secrets.DOCKER_USERNAME }}/${{ matrix.app-list }}:${latest_tag}" >> "$GITHUB_OUTPUT"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.app-list }}
          push: true
          tags: |
            ${{steps.version_step.outputs.version_tag}}
            ${{steps.version_step.outputs.latest_tag}}
          build-args: |
            ${{steps.version_step.outputs.version}}
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/${{ matrix.app-list }}
          readme-filepath: ./${{ matrix.app-list }}/README.md

