name: docker-push
on: push
jobs:
  docker:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags')
    strategy:
      matrix:
        include:
          - app: golang
          # - app: java
          # - app: nodejs
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      # - name: Extract Version
      #   id: version_step
      #   run: |
      #     echo "##[set-output name=version;]VERSION=${GITHUB_REF#$"refs/tags/v"}"
      #     echo "##[set-output name=version_tag;]${{ matrix.repo }}:${{ matrix.pre }}${GITHUB_REF##*-}"
      #     echo "##[set-output name=latest_tag;]${{ matrix.repo }}:${{ matrix.pre }}latest"

      # - name: Load .env file
      #   uses: aarcangeli/load-dotenv@v1.0.0
      #   with:
      #     path: ${{ matrix.app }}
      #     filenames: |
      #       .env
      #       .env.test
      #     quiet: true
      #     if-file-not-found: error
      - id: dotenv
        uses: falti/dotenv-action@v1.0.4
        with:
          path: ${{ matrix.app }}/.env
          export-variables: true
          log-variables: true
      #- id: dotenv
      #  uses: ${{ matrix.app }}/.env

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.app }}
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ steps.dotenv.outputs.docker_repo }}:${{ steps.dotenv.outputs.docker_version_tag }}
            ${{ secrets.DOCKER_USERNAME }}/${{ steps.dotenv.outputs.docker_repo }}:${{ steps.dotenv.outputs.docker_latest_tag }}
          build-args: |
            ${{ steps.dotenv.outputs.docker_version }}
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/${{ steps.dotenv.outputs.docker_repo }}
          readme-filepath: ./${{ matrix.app }}/README.md

