name: docker-test
on: push
jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app-list:
          - hi
          - docker
      fail-fast: false
    steps:
      - name: Extract Version
        id: version_step
        run: |
          echo "##[set-output name=version;]VERSION=${GITHUB_REF#$"refs/tags/v"}"
          echo "##[set-output name=version_tag;]$GITHUB_REPOSITORY:${GITHUB_REF#$"refs/tags/v"}"
          echo "##[set-output name=latest_tag;]$GITHUB_REPOSITORY:latest"
      - name: Webhook Notify - ${{ matrix.app-list }}
        uses: joelwmale/webhook-action@master
        with:
          username: ${{ secrets.WEBHOOK_URL }}
          headers: '{"Content-Type": "application/json"}'
          body: '{"msgtype": "markdown","markdown": { "content": "'$(cat ${{ matrix.app-list }}/README.md|sed 's/$/\\n/g'|tr -d '\n')'" }}'

